graph LR
    NewKernel --> Derivation --> CNNs("From Convolutions")
    Derivation --> Generalisation --> x["Currently: RBF -> Matern"]
    Derivation --> RidgeRegression("From Ridge Regression")

    CoreMath --> DeepNets("Deep Nets are Kernels")

    Optimisations --> GeneticOpti("Genetic Optimisation")
    Optimisations --> EvolutionaryLearning("Evolutionary Learning")
    Optimisations --> HybridGenetic("Hybrid Genetic")

    Quantum --> QKerns("Quantum Kernels")
    Quantum --> QKernsApplied("Quantum Kernels Applied")
    Quantum --> QKernsTraining("Training on Quantum Kernels")

    Other --> FeynmanPath("Feynman Path Integral as data analysis tool")



%% Study Order
%% - Intro
    %% - Derivation of Kernels from Ridge - https://youtu.be/wBVSbVktLIY
    %% - Ridge Regression
    %% - CNN Kern Relation https://homepages.inf.ed.ac.uk/rbf/HIPR2/log.htm
    %% - Qiskit QKerns https://qiskit.org/documentation/machine-learning/tutorials/03_quantum_kernel.html
    %% - Matern Kernel https://scikit-learn.org/stable/modules/generated/sklearn.gaussian_process.kernels.Matern.html
    %% - Kernel List -> Composition https://towardsdatascience.com/gaussian-process-kernels-96bafb4dd63e
%% - Mathematical STruct
    %% - DeepNets are Kerns https://youtu.be/ahRPdiCop3E
    %% - Kerns Podcast https://youtu.be/y_RjsDHl5Y4
    %% -
%% - Opti
    %% - Genetic Opti for SVM Kernels https://inpressco.com/wp-content/uploads/2013/06/Paper87713-716.pdf
    %% - Evolutionary Learning Kernel https://christian-igel.github.io/paper/EKL.pdf
    %% - Hybrid Genetic Algo for Regression https://www.sciencedirect.com/science/article/pii/S095741740800300X
%% - Quantum
%%     - Quantum Kernels Applied IBM ML https://youtu.be/LmQcSxgINis
%%     - Classification of QKerns https://medium.com/mlearning-ai/classification-using-quantum-kernels-tutorial-8a2f442fd188
%%     - Training on QKerns https://medium.com/qiskit/training-quantum-kernels-for-machine-learning-using-qiskit-617f6e4ed9ac
    %% -